In [17]:
import torch
import torch.nn as nn
from torch import topk
from torch import bmm
from torch import transpose
from torch import sum
import numpy as np

In [33]:
x = torch.tensor(np.random.randint(0,20, size=(2,2, 6)), dtype=torch.int32)
print(x)
x = x.repeat(1, 1, 2).view(2, 4, 6)
print(x)
b = torch.tensor(np.random.randint(0,20, size=(2,2, 6)), dtype=torch.int32)
print(b)
result = -2 * bmm(x, transpose(b, 2,1))
print(result) 

tensor([[[14,  0, 19,  1, 14,  7],
         [ 3, 14, 14, 14,  3, 14]],

        [[ 5,  5,  0,  3,  7,  3],
         [ 7,  1, 15,  8, 15,  7]]], dtype=torch.int32)
tensor([[[14,  0, 19,  1, 14,  7],
         [14,  0, 19,  1, 14,  7],
         [ 3, 14, 14, 14,  3, 14],
         [ 3, 14, 14, 14,  3, 14]],

        [[ 5,  5,  0,  3,  7,  3],
         [ 5,  5,  0,  3,  7,  3],
         [ 7,  1, 15,  8, 15,  7],
         [ 7,  1, 15,  8, 15,  7]]], dtype=torch.int32)
tensor([[[10, 11, 18, 14, 15,  4],
         [10, 15, 10,  6, 18, 14]],

        [[13, 14,  2,  0, 13, 19],
         [17,  4,  0,  2, 13, 11]]], dtype=torch.int32)
tensor([[[-1468, -1372],
         [-1468, -1372],
         [-1466, -1428],
         [-1466, -1428]],

        [[ -566,  -470],
         [ -566,  -470],
         [ -926,  -822],
         [ -926,  -822]]], dtype=torch.int32)


In [58]:
def distance(src:torch.Tensor, dis:torch.Tensor):
    """
    compute distance form every data in src to every data in dis
    params:
        src: (B, N, C) 
        dis: (B, M, C)
    return:
        distance: (B, N, M) 
    """
    _distance = -2 * bmm(src, transpose(dis, 2, 1)) # (B, N, M)
    _distance += torch.sum(src ** 2, -1, keepdim=True) # (B, N, M) + (B, N, 1)
    _distance += transpose(torch.sum(dis ** 2, -1, keepdim=True), 2, 1) # (B, N, M) + (B, 1, M)
    return torch.pow(_distance, -2)

In [59]:
a = torch.arange(0, 16, 1, dtype=torch.float32).view(2,2,4)
b = torch.ones((2,2,4), dtype=torch.float32)
b[:,1,:] = b[:,1,:] * 2
print(a, b)
dis = distance(a, b)
print(dis)

tensor([[[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.]],

        [[ 8.,  9., 10., 11.],
         [12., 13., 14., 15.]]]) tensor([[[1., 1., 1., 1.],
         [2., 2., 2., 2.]],

        [[1., 1., 1., 1.],
         [2., 2., 2., 2.]]])
tensor([[[2.7778e-02, 2.7778e-02],
         [1.3521e-04, 3.4294e-04]],

        [[1.1569e-05, 1.8904e-05],
         [2.5195e-06, 3.5069e-06]]])


In [ ]:
def topk_with_distance(src, dis, k):
    """
    find for every data in src its k-nearest neighbor from dis with index and distance 
    params:
        src: (B, N, C) 
        dis: (B, M, C)
        k: numbers to select from dis
    return:
        dis_index_distance: (B, N, k, 2) 
    """
    ...
    dis_index_distance = ...

    return dis_index_distance